export const ADD_RECIPE = "ADD_RECIPE";
export const MODIFY_RECIPE = "MODIFY_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_SINGLE_RECIPE = "GET_SINGLE_RECIPE";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
